


data:
  data_dir: /home/fredkeira/projects/assignment1-basics/token_to_id_outputs_tinystory 
  eot_id: 256   # 这里填 tokenizer 的 <|endoftext|> id
model:
  vocab_size: 10000
  context_length: 256
  d_model: 512
  num_layers: 4
  num_heads: 16
  d_ff: 1344
  rope_theta: 10000

optim:
  lr_max: 1e-3
  lr_min: 1e-3
  warmup_steps: 0
  cosine_steps: 0
  beta1: 0.9
  beta2: 0.995
  eps: 1e-8
  weight_decay: 0

train:
  batch_size: 1
  max_steps: 300
  seed: 1337
  max_l2_norm: 1.0
  save_every: 500
  eval_every: 200
  eval_steps: 20

runtime:
  device: cuda:1
  dtype: float32

experiment:
  run_dir: /home/fredkeira/data/cs336_training_result
  exp_name: tinystories_base
  resume: false
  resume_path: null

  debug_overfit: true
  one_step: false
  debug_shapes: false
  debug_norms: true